package container_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/The-Artificer-of-Ciphers-LLC/gsd-wired/internal/container"
)

func testCfg() container.ContainerConfig {
	return container.ContainerConfig{
		BeadsDoltDir: ".beads/dolt",
		HostPort:     "3307",
	}
}

// TestWriteComposeFragment_WritesValidYAML verifies the compose fragment is written correctly.
func TestWriteComposeFragment_WritesValidYAML(t *testing.T) {
	dir := t.TempDir()
	path, err := container.WriteComposeFragment(dir, testCfg(), false)
	if err != nil {
		t.Fatalf("WriteComposeFragment: unexpected error: %v", err)
	}

	if filepath.Base(path) != "gsdw.compose.yaml" {
		t.Errorf("expected filename 'gsdw.compose.yaml', got %q", filepath.Base(path))
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	content := string(data)

	checks := []string{
		"gsdw-dolt",
		"dolthub/dolt-sql-server:latest",
		"127.0.0.1:3307:3306",
		".beads/dolt:/var/lib/dolt",
		"DOLT_ROOT_HOST",
		"unless-stopped",
	}
	for _, want := range checks {
		if !strings.Contains(content, want) {
			t.Errorf("compose YAML missing %q\ncontent:\n%s", want, content)
		}
	}
}

// TestWriteComposeFragment_CommentHeader verifies the header comment is present.
func TestWriteComposeFragment_CommentHeader(t *testing.T) {
	dir := t.TempDir()
	path, err := container.WriteComposeFragment(dir, testCfg(), false)
	if err != nil {
		t.Fatalf("WriteComposeFragment: %v", err)
	}
	data, _ := os.ReadFile(path)
	content := string(data)

	if !strings.Contains(content, "Generated by: gsdw container start") {
		t.Errorf("compose YAML missing header comment 'Generated by: gsdw container start'\ncontent:\n%s", content)
	}
}

// TestWriteComposeFragment_RefusesOverwrite verifies force=false returns error when file exists.
func TestWriteComposeFragment_RefusesOverwrite(t *testing.T) {
	dir := t.TempDir()

	// First write succeeds.
	_, err := container.WriteComposeFragment(dir, testCfg(), false)
	if err != nil {
		t.Fatalf("first WriteComposeFragment: %v", err)
	}

	// Second write without force should fail.
	_, err = container.WriteComposeFragment(dir, testCfg(), false)
	if err == nil {
		t.Fatal("expected error when overwriting without force, got nil")
	}
	if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("error %q should mention 'already exists'", err.Error())
	}
	if !strings.Contains(err.Error(), "--force") {
		t.Errorf("error %q should mention '--force'", err.Error())
	}
}

// TestWriteComposeFragment_ForceOverwrite verifies force=true allows overwriting.
func TestWriteComposeFragment_ForceOverwrite(t *testing.T) {
	dir := t.TempDir()

	_, err := container.WriteComposeFragment(dir, testCfg(), false)
	if err != nil {
		t.Fatalf("first WriteComposeFragment: %v", err)
	}

	// Second write with force=true should succeed.
	_, err = container.WriteComposeFragment(dir, testCfg(), true)
	if err != nil {
		t.Fatalf("WriteComposeFragment with force: unexpected error: %v", err)
	}
}

// TestWriteComposeFragment_Healthcheck verifies healthcheck is included.
func TestWriteComposeFragment_Healthcheck(t *testing.T) {
	dir := t.TempDir()
	path, err := container.WriteComposeFragment(dir, testCfg(), false)
	if err != nil {
		t.Fatalf("WriteComposeFragment: %v", err)
	}
	data, _ := os.ReadFile(path)
	content := string(data)

	if !strings.Contains(content, "healthcheck") {
		t.Errorf("compose YAML missing healthcheck section\ncontent:\n%s", content)
	}
}
