package container

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// composeTemplate is the gsdw compose fragment template.
const composeTemplate = `# gsdw - Dolt database for beads graph storage
# Generated by: gsdw container start
# Use: docker compose -f docker-compose.yml -f gsdw.compose.yaml up

services:
  gsdw-dolt:
    image: dolthub/dolt-sql-server:latest
    container_name: gsdw-dolt
    restart: unless-stopped
    ports:
      - "127.0.0.1:{{.HostPort}}:3306"
    environment:
      - DOLT_ROOT_HOST=%
    volumes:
      - {{.BeadsDoltDir}}:/var/lib/dolt
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-P", "3306", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
`

// WriteComposeFragment writes a gsdw.compose.yaml fragment to dir.
// If force is false and the file already exists, returns an error.
// Returns the path to the written file.
func WriteComposeFragment(dir string, cfg ContainerConfig, force bool) (string, error) {
	hostPort := cfg.HostPort
	if hostPort == "" {
		hostPort = "3307"
	}

	destPath := filepath.Join(dir, "gsdw.compose.yaml")

	if !force {
		if _, err := os.Stat(destPath); err == nil {
			return "", fmt.Errorf("gsdw.compose.yaml already exists, use --force to overwrite")
		}
	}

	tmpl, err := template.New("compose").Parse(composeTemplate)
	if err != nil {
		return "", fmt.Errorf("parse compose template: %w", err)
	}

	data := struct {
		HostPort     string
		BeadsDoltDir string
	}{
		HostPort:     hostPort,
		BeadsDoltDir: cfg.BeadsDoltDir,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render compose template: %w", err)
	}

	if err := os.WriteFile(destPath, buf.Bytes(), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", destPath, err)
	}

	return destPath, nil
}
