package mcp

import (
	"context"
	"fmt"
	"regexp"
	"strings"

	mcpsdk "github.com/modelcontextprotocol/go-sdk/mcp"
)

// reqPattern matches GSD requirement ID labels like INFRA-01, MAP-02, SHIP-01.
// Compiled once at package level to avoid per-call cost.
var reqPattern = regexp.MustCompile(`^[A-Z]+-\d+$`)

// createPrSummaryArgs holds the arguments for the create_pr_summary MCP tool.
type createPrSummaryArgs struct {
	PhaseNum int `json:"phase_num"`
}

// prSummaryResult is the response for the create_pr_summary MCP tool.
type prSummaryResult struct {
	Title      string `json:"title"`
	Body       string `json:"body"`
	BranchName string `json:"branch_name"`
}

// handleCreatePrSummary implements the create_pr_summary MCP tool.
// It queries the beads graph for phase data and builds a structured PR summary (per D-04, D-05).
func handleCreatePrSummary(ctx context.Context, state *serverState, args createPrSummaryArgs) (*mcpsdk.CallToolResult, error) {
	if err := state.init(ctx); err != nil {
		return toolError(err.Error()), nil
	}

	// Query project bead for the project name (graceful fallback to "").
	projectName := ""
	projectBeads, err := state.client.QueryByLabel(ctx, "gsd:project")
	if err == nil && len(projectBeads) > 0 {
		projectName = projectBeads[0].Title
	}

	// Query all phase beads.
	phaseBeads, err := state.client.QueryByLabel(ctx, "gsd:phase")
	if err != nil {
		return toolError("failed to query phase beads: " + err.Error()), nil
	}

	// Find the target phase by matching phase number in metadata.
	var targetIdx = -1
	for i := range phaseBeads {
		if phaseNumFromMeta(phaseBeads[i].Metadata) == args.PhaseNum {
			targetIdx = i
			break
		}
	}
	if targetIdx == -1 {
		return toolError(fmt.Sprintf("no phase epic found for phase %d", args.PhaseNum)), nil
	}
	target := phaseBeads[targetIdx]

	// Build PR title: "Phase N: Phase Title" (GSD-familiar per D-05).
	title := fmt.Sprintf("Phase %d: %s", args.PhaseNum, target.Title)
	if projectName != "" {
		// Optionally include project context but keep it short.
		_ = projectName // project name included in fallback title below if no phase title
	}

	// Build PR body as markdown.
	var sb strings.Builder

	// Summary section with phase goal.
	sb.WriteString("## Summary\n\n")
	if target.Description != "" {
		sb.WriteString(target.Description)
		sb.WriteString("\n\n")
	} else {
		sb.WriteString("Phase ")
		sb.WriteString(fmt.Sprintf("%d", args.PhaseNum))
		sb.WriteString(" ship\n\n")
	}

	// Requirements section — filter labels matching req pattern.
	sb.WriteString("## Requirements\n\n")
	reqCount := 0
	for _, label := range target.Labels {
		if reqPattern.MatchString(label) {
			sb.WriteString("- ")
			sb.WriteString(label)
			sb.WriteString("\n")
			reqCount++
		}
	}
	if reqCount == 0 {
		sb.WriteString("_(none listed)_\n")
	}
	sb.WriteString("\n")

	// Phases section: checklist of all phases with status.
	sb.WriteString("## Phases\n\n")
	for i := range phaseBeads {
		b := &phaseBeads[i]
		phaseNum := phaseNumFromMeta(b.Metadata)
		if b.Status == "closed" || b.Status == "done" {
			sb.WriteString(fmt.Sprintf("- [x] Phase %d: %s\n", phaseNum, b.Title))
		} else {
			sb.WriteString(fmt.Sprintf("- [ ] Phase %d: %s\n", phaseNum, b.Title))
		}
	}
	sb.WriteString("\n")

	// Footer.
	sb.WriteString("---\n_Generated by gsd-wired_\n")

	// Build branch name: "ship/phase-N" (lowercase, simple).
	branchName := fmt.Sprintf("ship/phase-%d", args.PhaseNum)

	return toolResult(&prSummaryResult{
		Title:      title,
		Body:       sb.String(),
		BranchName: branchName,
	})
}
